name = "PermutedArrays"
uuid = "aa3a806a-e146-4a0b-abc5-6bb34b5dedb7"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
